# Generated by Django 3.1.2 on 2021-10-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('price', models.FloatField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.TextField()),
                ('slug', models.SlugField(verbose_name={'slug': ('name',)})),
            ],
        ),
    ]
